### PR TITLE
Require Boost version 1.74

### PR DESCRIPTION
**Pull request by bredelings**
I think that linux compiles already need to download and compile boost, with the version in the examples being 1.71
This PR bumps that to 1.71 and makes it a requirement.
The latest version is 1.77.
I don't think this would affect mac or windows.

### CODE REVIEW

**Comment by bredelings** [comment]
Per the meeting today, we should have consensus on this.

**Review by davidcerny — APPROVED** [review]

**Comment by willpett** [comment]
Sorry I was kind of out of the loop on this when it got discussed. Linux builds definitely don't need to compile boost. The version in the current Ubuntu repositories is 1.71, which is found and used just fine when building RevBayes. This update makes it necessary to install/compile a separate version. Why do we need 1.74? If the need isn't super urgent, I'd say we should roll this back.

**Comment by bredelings** [comment]
This is needed for PR #211.

Hmm... needing to compile a newer version of boost by hand is indeed annoying.  Are you talking about CI, or do you have a machine where ubuntu only has 1.71?

**Comment by bredelings** [comment]
mmmm.... so we needthe `boost::mp11:tuple_transform` function, which was added in version 1.74.

Possibly we could just steal the definition from the boost:

```
template<class F, class... Tp, std::size_t... J>
BOOST_MP11_CONSTEXPR auto tuple_transform_impl( integer_sequence<std::size_t, J...>, F const& f, Tp&&..>
    -> decltype( tp_forward_v( tuple_apply( f, tp_extract<J>( std::forward<Tp>(tp)... ) )... ) )
{
    return tp_forward_v( tuple_apply( f, tp_extract<J>( std::forward<Tp>(tp)... ) )... );
}

```

**Pull request merged**
