### PR TITLE
Changed simulateDivergenceTime to avoid overflow.

### PR DESCRIPTION
**Pull request by brpetrucci**

### CODE REVIEW

**Comment by bredelings** [comment]
This all looks good.  Thanks for checking my math!  You were right that the first and second cases agree, so the only problem was the divide by zero when dividing by exp(-age*x).  I also like that you've refactored the formula to look like (... + age).

**Review by bredelings — CHANGES_REQUESTED** [review]
What do you think about adding two assert statements:
- `assert(age >= 0)` at the beginning of the function?
- `assert(0 <= t and t <= age)` at the end of the function?

**Comment by brpetrucci** [comment]
> What do you think about adding two assert statements:
> 
> * `assert(age >= 0)` at the beginning of the function?
> * `assert(0 <= t and t <= age)` at the end of the function?

That sounds good! Do I just add those two lines, or are there headers or something of the sort I need to change as well?

**Comment by bredelings** [comment]
Hmm, perhaps you should add `#include <cassert>` as well.  Often some other header includes <cassert>, so it might compile without it, but it can't hurt to add it.

**Comment by brpetrucci** [comment]
Made those changes! Let me know what you think.

**Review by bredelings — APPROVED** [review]

**Pull request merged**
