### PR TITLE
dnInverse

### PR DESCRIPTION
**Pull request by ms609**
This pull request addresses #492 by adding a new distribution function `dnInverse(x)` that inverts the probabilities associated with the distribution `x`.

Queries:
- Does this belong as a `dn` function?  It has some parallels with the new `tn` transformation functions, though it cannot be straightforwardly accommodated in the TransformedDistribution class
- How can the distribution access the underlying properties (e.g. `taxa`) of a distribution of type `AbstractCharacterData` in order to correctly print its output?

I believe that the implementation is mathematically sound and functions, so think this could be ready to merge – though it would be nice to also address these outstanding issues, for which input from experienced developers would be welcome!

### CODE REVIEW

**Comment by ms609** [comment]
I've discovered an issue with the implementation, which I don't see an obvious way to address.  The probability is calculated correctly on the first call to `.lnProbability()`, but not on subsequent calls.  Here's a revised test file:

```rb
seed(42)

exp ~ dnExp(1)
exp.clamp(42)

inv_exp ~ dnInv(dnExp(1))
inv_exp.clamp(42)
print("Expect: 42", -exp.lnProbability(), inv_exp.lnProbability())

chars <- readDiscreteCharacterData("../validation/data/bears.nex")

taxa <- chars.names()
n_taxa <- chars.size()
n_edge <- 2 * n_taxa - 3

topology ~ dnUniformTopology(taxa)
br_lengths ~ dnDirichlet( rep(1.0, n_edge) )
phylogeny := treeAssembly(topology, br_lengths)

k ~ dnUniform(1, 10)
kRates := [ [ 0, k],
            [ 1, 0] ]
qK := fnFreeK(kRates)
phy ~ dnPhyloCTMC(tree = phylogeny, Q = qK, type = "Standard")
phy.clamp(chars)

invPhy ~ dnInv(dnPhyloCTMC(tree = phylogeny, Q = qK, type = "Standard"))
invPhy.clamp(chars)
invPhy

k.clamp(1)
print(k, "Expect equal:", -phy.lnProbability(), invPhy.lnProbability())
# succeeds
k.clamp(5)
print(k, "Expect equal:", -phy.lnProbability(), invPhy.lnProbability())
# does not succeed: -phy decreases where invPhy increases.
k.clamp(6)
print(k, "Expect equal:", -phy.lnProbability(), invPhy.lnProbability())
# same again
```

Can anyone shed light on what might be happening here?

Thanks!

**Comment by bjoelle** [comment]
when you're doing `setValue` and `redrawValue` it looks as if you're only updating the value for the base disribution, not the value stored by `InverseDistribution` so that may be part of the issue
does it also happen with the `dnExp` variable or just with the more complex model ? can you check that `qK`, ìnvPhy` and `phy` are updated as they should be ?

**Comment by ms609** [comment]
Thanks for taking a look.  

With `dnExp` I see:
```rb
inv_exp ~ dnInv(dnExp(1))
inv_exp.clamp(42)
print("Expect: 42", -exp.lnProbability(), inv_exp.lnProbability())
# Success

exp.clamp(21)
inv_exp.clamp(21)
print("Expect: 21", -exp.lnProbability(), inv_exp.lnProbability())
# Success
```

but this feels slightly different as I'm clamping the value drawn from the distribution rather than one of its parameters – I'm not sure what an equivalent test would look like.

I'll look into your other suggestions anon

**Comment by ms609** [comment]
Thanks for taking a look.  I've worked through your suggestions as best I can:

> `setValue` and `redrawValue`

This is an interesting observation. 
- `setValue` currently updates the base distribution via `dist->setValue()`; I have added `this->value`.
- `redrawValue` currently updates the value stored by `InverseDistribution` (`this->value`).  I have added a call to `dist->redrawValue()` here, to also update the base distribution.  Neither of these additions have fixed the issue.

As `computeLnProbability` only makes use of the base distribution, the value of the  `InverseDistribution` should not be relevant to this calculation. Perhaps I could even remove the code that modifies `this->value` – are there other side-effects of setting `this->value` that might influence the calculation or updating of the model?

> does it also happen with the dnExp variable or just with the more complex model ?

With `dnExp` I see:
```rb
inv_exp ~ dnInv(dnExp(1))
inv_exp.clamp(42)
print("Expect: 42", -exp.lnProbability(), inv_exp.lnProbability())
# Success

exp.clamp(21)
inv_exp.clamp(21)
print("Expect: 21", -exp.lnProbability(), inv_exp.lnProbability())
# Success
```

but this feels slightly different as I'm clamping the value drawn from the distribution rather than one of its parameters – I'm not sure what an equivalent test would look like.

> can you check that qK, invPhy and phy are updated as they should be ?

Printing `qK` confirms that it is updated as expected; can you suggest how I could test that updates to `invPhy` and `phy` are correct?

**Comment by bjoelle** [comment]
sorry I was thinking of `phylogeny` actually, `phy` is clamped so it shouldn't move
but probably the best way is to run all of this in a debugger so you can directly check what values are used to do the likelihood calculation and whether something is not being updated correctly

**Comment by ms609** [comment]
Using a debugger sounds like the way to go.  I'd been shying away from this because I feared the learning curve – fears which have proven well founded!  I just about got things set up when I ran up against the "file too big" issue you reported in #444. Did you eventually find a workaround for that issue?

**Comment by bjoelle** [comment]
Unfortunately my current workaround is to do all my RevBayes-related work on my Linux laptop lol

Also I didn't mention it before but if you manage to make it work and would like some more introduction to debuggers/how things work in RevBayes I'm happy to do so, just tell me and we can have a Zoom call or something

**Comment by ms609** [comment]
That's very generous, thank you!  I've dug out my decade-old Ubuntu machine, which is going to take a while to upgrade to current packages. An orientation session once (if?) I manage to get RevBayes built could be very helpful.

**Comment by ms609** [comment]
Thanks to @bjoelle's patient coaching I've been able to fix the aforementioned issues: `print(invPhy)` now reports the values set in the object itself (copied from the base dist), and overriding the `touch` function to also touch the base distribution means that the likelihood is now calculated correctly.

**Comment by ms609** [comment]
I've got two branches in a tangle here so I'm closing this PR and have created a new one from `revbayes/dnInverse` at #562.

**Pull request closed without merging**
