### PR TITLE
Document time

### PR DESCRIPTION
**Pull request by ms609**
This PR explains the effect of each parameter to `time()`.
(I'm guessing `fromBeginning` because it's currently broken – #571)

### CODE REVIEW

**Comment by bredelings** [comment]
Hmm.... yeah, the number of seconds does seem wrong:
```
> t=time()
> t/60/60/24/365.25
   624822.2
```

The term "Julian date" confused me.  I thought that meant "without gregorian calendar corrections", or something like that.

https://www.longpelaexpertise.com.au/toolsJulian.php

**Comment by bredelings** [comment]
This is fun: https://en.wikipedia.org/wiki/Julian_day

**Comment by ms609** [comment]
> 624822.2

I think `fromBeginning` gives milliseconds – throw in another `/1000` and 62.48222 sounds closer to (but not quite!) the number of years since 1970-01-01.

**Review by bredelings — APPROVED** [review]

**Comment by davidcerny** [comment]
@ms609 That doesn't work out – following that assumption, you'd need to divide by 10,000 rather than 1000 to get ~62.4 years, and even then the result would be off by >7 years, as you point out.

For some reason, boost's "earliest representable date" (the `min_date_time` constant used in `Func_time.cpp`) is 1400-Jan-01 00:00:00:
https://www.boost.org/doc/libs/1_33_1/doc/html/date_time/gregorian.html
https://stackoverflow.com/a/25084661

`time("fromBeginning")` gives the number of milliseconds elapsed since that date.

**Pull request merged**
