### PR TITLE
Added changelog

### PR DESCRIPTION
**Pull request by bjoelle**
to make releases easier and provide a record of improvements made

### CODE REVIEW

**Review by wadedismukes — COMMENTED** [review]
I think we should add a release action to workflow that adds this to the release notes. If you disagree it looks good otherwise.

**Comment by wadedismukes** [comment]
> I think we should add a release action to workflow that adds this to the release notes. If you disagree it looks good otherwise.
See this action below:
https://github.com/actions/create-release

Basically we just make it happen whenever we merge development into master. (rather than on a schedule or on push or something.

**Comment by bjoelle** [comment]
@wadedismukes adding it to the release notes is a good idea for sure !
as I remember the release process was mostly manual last time, but we can take another look at automating it for the next one
I was also planning to link to that file from the website once it's accepted

**Review by wadedismukes — APPROVED** [review]
Other than the above comments looks good (I will add a tab in Projects for the stuff we talked about as it is not pressing).

**Comment by wadedismukes** [comment]
> @wadedismukes adding it to the release notes is a good idea for sure !
> as I remember the release process was mostly manual last time, but we can take another look at automating it for the next one
> I was also planning to link to that file from the website once it's accepted

Oh that sounds good. I like the idea of having it on the website. Not sure why I didn't merge this before.

**Pull request merged**
