### PR TITLE
Restarting FBD trees properly from checkpoint

### PR DESCRIPTION
**Pull request by bjoelle**
This PR is designed to fix issue #483 by restoring fossil age ranges correctly when restarting an FBD analysis from checkpoint, using a similar method as what David did for initial trees

Bonus fix: fixed inconsistent orderings of the taxon map so the MRCA references still work properly

### CODE REVIEW

**Comment by bjoelle** [comment]
Update: I've also added sorting to the vector returned by `Tree::getFossilTaxa` which hopefully should solve #482 as well

**Review by davidcerny — COMMENTED** [review]
Hmm... based on @minghao-du's test cases, this unfortunately seems to fix neither #482 nor #483 – at least not fully.

For issue #482, the tip ages no longer have staircase-like traces, but they are not successfully re-initialized either. Once the analysis has been restarted, their traces just remain completely flat, with no moves ever getting accepted:

Screenshot 2024-07-09 at 11 08 18

(Incidentally, I seem to remember us running into this exact same problem before, but I can't find the corresponding issue in the repo. Nor do I remember if it's ever been successfully resolved.)

For issue #483, instead of the re-initialized analysis getting stuck at iteration 1200, I now can't re-initialize it all. Instead, I'm running into the following error:

```
> restart = TRUE
> source("/Users/David/Downloads/issue483/scripts/FBD_Model.Rev")
   Processing file "/Users/David/Downloads/issue483/scripts/FBD_Model.Rev"
   Successfully read one character matrix from file 'data/mol_1.nex'
   Successfully read one character matrix from file 'data/morph_1.nex'
   Processing file "scripts/model_ME.Rev"
   Processing of file "scripts/model_ME.Rev" completed
   Processing file "scripts/model_FBD.Rev"
   Processing of file "scripts/model_FBD.Rev" completed
   Processing file "scripts/model_JC.Rev"
   Processing of file "scripts/model_JC.Rev" completed
   Processing file "scripts/model_Morph.Rev"
   WARNING: There are 1 characters incompatible with the specified coding bias. These characters will be excluded.
   Processing of file "scripts/model_Morph.Rev" completed
   Processing file "scripts/model_MCMC.Rev"
   Error:	Tip names of the initial tree do not match the taxon names.
   Error:	Problem processing line 16 in file "scripts/model_MCMC.Rev"
   Error:	Problem processing line 48 in file "/Users/David/Downloads/issue483/scripts/FBD_Model.Rev"
```

**Comment by bjoelle** [comment]
@davidcerny thanks for testing this - I will look into this further !

**Comment by davidcerny** [comment]
Ah, you're 100% right – that's actually a problem with my `TreeUtilities::startingTreeInitializer()` function. Still worth fixing for sure, and it's weird to me that it only resurfaces when restarting the analysis rather than right from the outset, but it's not something that should prevent us from going ahead with this PR.

Would you like me to approve now, or do you want to give a try to fixing the issue with stuck tip ages first?

**Comment by bjoelle** [comment]
@davidcerny I don't have the time to work on this before next week, so I propose that I revert the last 2 commits related to fossil ordering, and then we can merge this as a fix for 483 ? thanks !

**Comment by bjoelle** [comment]
actually, I get likelihood=-inf when restarting (which is why the ages don't move anymore - actually nothing moves) but that also happens on `development` so it seems unrelated to my changes

**Review by davidcerny — APPROVED** [review]

**Pull request merged**
