### PR TITLE
Stop tree rescaling from changing ages of SAs or their direct parent

### PR DESCRIPTION
**Pull request by bjoelle**
Fixes issue #557 and adds some sanity checks to (hopefully) stop this from happening again

### CODE REVIEW

**Comment by davidcerny** [comment]
This is great; thank you so much, Joëlle! I'm wondering if we should try to be proactive and see if other node time proposals could benefit from the same fix/extra condition :

- [`mvNodeRateTimeSlideUniform`](https://github.com/revbayes/revbayes/blob/master/src/core/moves/proposal/tree/NodeRateTimeSlideUniformProposal.cpp)
- [`mvNodeTimeScale`](https://github.com/revbayes/revbayes/blob/master/src/core/moves/proposal/tree/NodeTimeScaleProposal.cpp)
- [`mvNodeTimeSlidePathTruncatedNormal`](https://github.com/revbayes/revbayes/blob/master/src/core/moves/proposal/tree/NodeTimeSlidePathTruncatedNormalProposal.cpp)
- [`mvNodeTimeSlideUniform`](https://github.com/revbayes/revbayes/blob/master/src/core/moves/proposal/tree/NodeTimeSlideUniformProposal.cpp)
- [`mvNodeTimeSlideUniformAgeConstrained`](https://github.com/revbayes/revbayes/blob/master/src/core/moves/proposal/tree/NodeTimeSlideUniformAgeConstrainedProposal.cpp)

I should be able to look into these later today...

**Comment by davidcerny** [comment]
Okay, I added the extra check to all other equivalent node age moves I could find. Two quick notes:

- [`mvNodeTimeSlidePathTruncatedNormal`](https://github.com/revbayes/revbayes/blob/master/src/core/moves/proposal/tree/NodeTimeSlidePathTruncatedNormalProposal.cpp) and [`mvNodeTimeSlideUniformAgeConstrained`](https://github.com/revbayes/revbayes/blob/master/src/core/moves/proposal/tree/NodeTimeSlideUniformAgeConstrainedProposal.cpp) sort of do their own thing. It's not clear to me if they suffer from the same problem, and if so, how to fix them.
- [`mvNodeTimeSlideUniform`](https://github.com/revbayes/revbayes/blob/master/src/core/moves/proposal/tree/NodeTimeSlideUniformProposal.cpp) already includes the extra check, but in a slightly different form: instead of just `isSampledAncestorParent()`, it uses `isSampledAncestorTipOrParent()`. Not sure how significant this difference is.

**Comment by davidcerny** [comment]
I can confirm this fixes the hanging problem described in #557. It doesn't solve #544 – the same dataset/seed combination now triggers the exception newly added to `TopologyNode::setAge()`. I'm wondering if an analysis-terminating exception is really what we want to do here – couldn't we just reject the move that tries to set a node's age to an illegal value?

**Comment by bjoelle** [comment]
@davidcerny we can certainly reject the move instead, but that also has to be done at the move level, `TopologyNode::setAge()` cannot do it - so my view is, if we have to change the move we might just as well do the right thing in the first place
imo raising an exception is the right thing to do - it's not supposed to happen, so either the calling code expects it and deals with it by catching the exception, or we crash because it's better than getting into an invalid state

**Comment by bjoelle** [comment]
with this PR I can now run the script from #544 until iteration 150,000 without issue - @davidcerny can you confirm if this is still an issue ?

**Comment by bjoelle** [comment]
With this PR I can now run the script from issue #544 for 160,000 iterations without issue
@davidcerny can you confirm if this resolves your issue ?

**Comment by davidcerny** [comment]
@bjoelle I can confirm it doesn't, unfortunately. Are you setting `seed(234)` by any chance? When I do that, the analysis throws the following error after 110,000 iterations:

```
   Error:	New age of taxa Gamatavus_antiquus incompatible with age range
   Error:	Problem processing line 250 in file ""/Users/David/Downloads/fbd_mvslice_crash/test.Rev""
```

**Comment by bjoelle** [comment]
thanks for the additional information ! 
it looks like this may happen because the root age has a separate move on it - so when it is being modified and the root is an SA, it tries to update the node age as well and then that fails

I'm not sure what is the best solution for this honestly, because the root age move has no reference to the tree so it cannot check for SAs - I think having a separate move on the root age may just be a bad idea ?

**Comment by bjoelle** [comment]
ok I've disabled the exception for now while we decide what to do about it, and added checks to the root time proposals
if you agree @davidcerny maybe we can merge this first and then look deeper into the root age related issues ?

**Review by davidcerny — APPROVED** [review]
Thank you @bjoelle! For what it's worth, after an absurd amount of tinkering with the original script from #544, I managed to find a combination of settings that allowed me to verify what happens to the problematic tip age when the newly added warning is emitted: seed = 234, burnin = 480,000 iterations, sampling = 20,000 iterations, move schedule = "single", frequencies of all monitors (log, screen, file) set to 1 in order to sample after every single attempted move. During the sampling period, the warning was emitted 31 times, always for the same taxon. However, when I checked the age of this taxon in the sampled trees, it was within the specified range every single time (i.e., in all 20,000 samples). So everything works as intended, and as far as I'm concerned, this PR solves #544. :)

I've made a cosmetic change to the warning ("taxa" is plural; the singular is "taxon").

I've pre-emptively approved the PR, but I do have one last question (which I already asked above, but we both understandably got sidetracked): is the condition that you've added:

```
while ( node->isRoot() || node->isTip() || node -> isSampledAncestorParent())
```

perfectly equivalent to the following condition that was already present in `NodeTimeSlideUniformProposal`?

```
if (not node.isRoot() and not node.isTip() and not node.isSampledAncestorTipOrParent())
```

If not, then I guess one is either too lax or too strict. Based on the syntax choices, it looks to me like the latter may have been written by @bredelings – feel free to chime in, Ben! :)

**Comment by bjoelle** [comment]
@davidcerny sorry I had missed that question
I think the condition in `NodeTimeSlideUniformProposal` is slightly redundant - if the node is not a tip then by definition it cannot be a SA tip
but both conditions should give the exact same results yes

**Pull request merged**
