### PR TITLE
Correctly updating phylogenetic likelihood when site mixture probability changes

### PR DESCRIPTION
**Pull request by jsigao**
This PR is supposed to fix an issue identified in this [bug report #436](https://github.com/revbayes/revbayes/issues/436) by @jembrown. The phylogenetic likelihood wasn't updated when only the site mixture probability vector, v<sub>mix</sub>---i.e., either the site rate probs or the site matrix probs---changed at an MCMC step. This PR Introduced an additional flag to allow revbayes to execute the `sumRootLikelihoods` function (instead of doing nothing, which was the cause of this bug) without having to recomputing any of the partials when only v<sub>mix</sub> is updated.

The bug fix is validated by comparing the output of running the example dataset provided in [#436](https://github.com/revbayes/revbayes/issues/436). The two computation options (as pointed out by @bredelings) when only v<sub>mix</sub> changes---1) recomputing the phylogenetic likelihood entirely and 2) only executing `sumRootLikelihoods` without updating any partials---produce identical outputs and both achieve the expected behavior stated in [#436]: 

> The mixture weights (mix[1] and mix[2]) should be correctly estimated as ~10% and ~90%.

Option 2 is chosen to be the implementation of this bug fix because of its computational efficiency. Option 2 is about 25% faster than option 1 for the example dataset, consistent with the specified 25% of proposal weight on updating v<sub>mix</sub>.

### CODE REVIEW

**Comment by bredelings** [comment]
Thanks @jsigao for looking into this carefully and checking the times and accuracy!

Hmm... so one other option would be to remove the `mixture_probs_dirty` flag, and to do `this->lnProb = sumRootLikelihood();` unconditionally.  It seems slight simpler, and maybe more robust.  What do you think?

**Comment by jsigao** [comment]
Thanks for the suggestion @bredelings! I'd be fine with always doing `this->lnProb = sumRootLikelihood(); `unconditionally. I guess though I don't know, as you previously mentioned, if there is any case that the `computeLnProbability` function in phyloctmc is called but the likelihood does not need to be updated at all. Even that may happen, considering that the computation cost of `sumRootLikelihood` should be fairly small, perhaps it'd still be more robust and virtually as efficient as it could be to always executing `sumRootLikelihood` unconditionally?

**Comment by bredelings** [comment]
As you say, if there is some case where this is a slowdown, probably it is not much.  And I think we should value robustness over efficiency here.  So, if you are OK with it, lets do `this->lnProb = sumRootLikelihood();` unconditionally!

**Comment by jembrown** [comment]
This plan sounds good to me. Do we need an additional commit to do `this->lnProb = sumRootLikelihood();` unconditionally?

**Review by bredelings — APPROVED** [review]

**Pull request merged**
