### PR TITLE
fixing a bug in mnSiteMixtureAllocation

### PR DESCRIPTION
**Pull request by mikeryanmay**
There was a bug in mnSiteMixtureAllocation that transposed the site-specific allocations for site-rates and site matrices. I fixed it!

### CODE REVIEW

**Comment by mikeryanmay** [comment]
Very confused about the pull request failing all of the checks! I created this branch from development within the last 15 minutes, so it's unclear to me what the problem is. Any assistance would be greatly appreciated.

**Comment by bjoelle** [comment]
@mikeryanmay it's not RevBayes, there is an issue with the Boost installation

**Comment by bredelings** [comment]
Ah, this is trying to download boost from bintray, but bintray is going away.

**Comment by bredelings** [comment]
"Instead of: `https://dl.bintray.com/boostorg/release`/ you should use `https://boostorg.jfrog.io/artifactory/main/release/` to retrieve boost releases."

**Comment by bjoelle** [comment]
@bredelings I've updated the link on the branch `actions_fix`, will PR if it passes

**Comment by bjoelle** [comment]
builds are fixed in PR #173

**Comment by bredelings** [comment]
Is this also broken in `drawStochasticCharacterMap` (same file)?

Perhaps the common code can be factored out into an inline function?

**Comment by mikeryanmay** [comment]
Yes, it's also broken there. Thanks for catching that. 

An easy solution is to have `drawStochasticCharacterMap` call `getSampledMixtureComponents`. Are you suggesting turning `getSampledMixtureComponents` into an inline member function (the common code is effectively the entire body of `getSampledMixtureComponents`)?

**Comment by bredelings** [comment]
Hmm... I guess I was actually thinking of an inline function that decomposed an arbitrary index into its `rate_component` part and its `matrix_component` part.

The logical thing is to make it return a pair<int,int>, but probably the current method of returning the results through parameters that are passed by reference would be better for now.  Until c++17, we cannot do e.g. `auto [x,y] = function_that_returns_a_pair();`.

Anyway, I think whatever way you implement it is fine as long as the code isn't duplicated.  So, if you want to just call getSampledMixtureComponents from drawStochasticCharacterMap, then I'm fine with that, although that wasn't what I was originally thinking.

**Comment by mikeryanmay** [comment]
Yes, I see the logic in such a function. I think I'd rather fix this straightforwardly, then return later for a more serious overhaul (there are other performance issues with this code that need to be cleaned up).

**Comment by bredelings** [comment]
OK, then perhaps just do something (anything) to fix `drawStochasticCharacterMap` and make sure that the comment there is correct, or remove it?

**Comment by mikeryanmay** [comment]
Done! (I think)

**Review by bredelings — APPROVED** [review]

**Comment by bredelings** [comment]
Ah, right, I didn't notice.  Great!

**Pull request merged**
