### PR TITLE
fix probability constructor function

### PR DESCRIPTION
**Pull request by hoehna**
This should make a simple and RevBayes consistent fix to the discussion https://github.com/revbayes/revbayes/issues/391

It also fixes this issue: https://github.com/revbayes/revbayes/issues/348

### CODE REVIEW

**Review by bredelings — CHANGES_REQUESTED** [review]
Thanks @hoehna.

1. Can we make the corresponding changes to RealPos.cpp at the same time, and synchronize them? 
2. RealPos doesn't have any argument rules, and doesn't have a setConstParameter( ) member function.  Why is that?
3. RealPos checks the parameter values when constructing from  a TypedDagNode<double> -- we should do this in Probability.cpp also I think.
4. Probability.cpp should check that the value is in [0,1] when we do setConstParameter( ) as well.

**Comment by davidcerny** [comment]
This solves the problem with a single line change, which is great. My only complaint would be that the error message we get when trying to create an invalid probability:

```
a <- Probability(-0.0000000001)
   Error:	Argument or label mismatch for function call.
   Provided call:
   Probability (Real<constant> )
   
   Correct usage is:
   Probability (Probability<any> x)
```

is decidedly less informative than the exception we throw in one of the constructors (`Creation of Probability with value x=<> outside standard probabilities (0,1)`).

@bredelings:

> Probability.cpp should check that the value is in [0,1] when we do setConstParameter( ) as well.

So I've been trying to implement a check like that, and found it surprisingly difficult. The best I could come up with was:

```
double test = std::stod( var->getRevObject().getDagNode()->getValueAsString() );

if ( name == "x" && test >= 0 && test <= 1 )
{
    real = var;
}
else if ( (name == "x" && test < 0) || (name == "x" && test > 1) )
{
    throw RbException() << "Creation of " << getClassType() << " with value x=" << test << " outside standard probabilities (0,1)";
}
```

But this is not very reliable; it doesn't prevent the creation of invalid probabilities whose string representation is rounded / truncated:

```
> Probability(-3)
   Error:	Creation of Probability with value x=-3 outside standard probabilities (0,1)
> Probability(1.00001)
   Error:	Creation of Probability with value x=1.00001 outside standard probabilities (0,1)
> Probability(1.000001)
   1.000001
```

I was mostly surprised that `DagNode` has no simple `.getValue()` method, only `.getValueAsString()` and `.getValueAsJSON`.

**Comment by bredelings** [comment]
@hoehna It seems like requiring the input to Probability to be a Probability defeats the purpose of Probability in some cases.

Looking for `Probability( )` in the tutorials, I see stuff like:
``` R
mix_p <- Probability(1.0 - expected_number_of_mass_extinctions/NUM_BREAKS)
```
and
``` R
rho       = Probability(extant_taxa / total_taxa)
```

It seems like the point here is that Probability can take a `Real` or `RealPos` and return a `Probability`.  It so, then the meaning of `Probability( x )` is something like
> I assume that `x` is in [0,1] even though it has type Real.

However, if `Probability( 1 - p )` now fails because `1-p` isn't **known* to be a Probability, then this defeats the point.  We want to be able to do:
``` R
> x ~ dnBinomial(size=10, p=0.5)
> y ~ dnBinomial(size=10, p = x/10)
   Error:	Argument or label mismatch for function call.
   Provided call:
   dnBinomial (Natural<constant> 'size',
               RealPos<deterministic> 'p' )
   
   Correct usage is:
   dnBinomial (Probability<any> p,
               Natural<any> size)
   
> y ~ dnBinomial(size=10, p = Probability(x/10))
```

Am I overlooking something?

**Comment by bredelings** [comment]
Another possible route we can take is illustrated by Pr #410

**Pull request closed without merging**
