### PR TITLE
Make sure ModelVector is normalized when converting to Simplex

### PR DESCRIPTION
**Pull request by willpett**
When testing whether a `ModelVector` can be converted a `Simplex`, the only check in place was that each element is convertible to a `Probability`. This implements a check to make sure the vector is also normalized. This solves #93.

### CODE REVIEW

**Comment by willpett** [comment]
Looks like this is failing in `testiphy` because apparently the vector `freqs = [0.4,0.3,0.2,0.1]` doesn't sum to 1.0. Unfortunately, due to floating point representation, there no guarantee that a vector will sum to 1.0 internally... So a vector may fail to convert to `Simplex` even if it sums to 1.0 in the Rev script.

**Comment by bredelings** [comment]
So, whereas #102 is designed to make conversions from ModelVector to Simplex work by deriving Simplex from ModelVector only, this PR is designed to make conversions from ModelVector to Simplex work by checking that the ModelVector has entries that sum to 1?

**Comment by bredelings** [comment]
Is the ModelVector value actually replaced with a Simplex value?  Or is ModelVector dynamic_cast-ed to Simplex?

**Comment by willpett** [comment]
Whether a variable is actually replaced with its converted value depends on the context (see #101). This PR just allows ModelVector to be used when a Simplex is required under the condition that its values are normalized.

**Review by bjoelle — APPROVED** [review]

**Pull request merged**
