### PR TITLE
Pre-release checklist

### PR DESCRIPTION
**Pull request by willpett**
Release v1.2 Lagerstätte

### CODE REVIEW

**Comment by bredelings** [comment]
I'd like to get the #220 merged before release.

**Comment by bredelings** [comment]
Hey Will, perhaps the NEWS file should continue to contain info about past releases?

**Comment by willpett** [comment]
Hm, I guess I was thinking the news file just contains changes since the last release. People can just go check the news file for each release to see the changes. Otherwise maybe we call it the Change Log?

**Comment by bredelings** [comment]
I think that NEWS files traditionally look like this:

https://fossies.org/linux/gdb/gdb/NEWS

So, they contain information on the last few releases, and are aimed at users instead of developers.  I think some projects contain Changelog files in addition to a NEWS file, but they are more granular and aimed at developers.  Now that you can run `git log`, I suspect many projects have dropped Changelog files.

**Review by bredelings — APPROVED** [review]

**Pull request merged**
