### PR TITLE
Sampling fossil ages with dnConstrainedTopology + initial tree

### PR DESCRIPTION
**Pull request by davidcerny**
This PR is intended to fix issue #477, which turned out to be essentially the same as issue #354 except that it affected `dnConstrainedTopology` rather than `dnBDSTP`: supplying a user-specified initial tree overwrote the ages of fossil taxa (min = max = 0), making it impossible to sample them from the [min, max] intervals specified in a taxon info file. I have added extra code to the `TopologyConstrainedTreeDistribution` constructor that checks whether a starting tree is present and whether it contains fossils. If both of these conditions are satisfied, it runs `TreeUtilities::startingTreeInitializer()` on the initial tree to replace each of its tips with the previously specified taxon of the same name. As with `dnBDSTP`, a new `ageCheckPrecision` argument has been added to specify how strict we should be when assessing whether the ages of the fossils in the initial tree are compatible with the age ranges specified in the taxon info file.

I have verified that the code works as intended, and that it doesn't affect other uses of `dnConstrainedTopology` (e.g., when it is used for non-clock trees).

### CODE REVIEW

**Comment by bjoelle** [comment]
@davidcerny I'm not sure about putting special handling code into the topology class, especially things that are directly duplicated from another distribution - if we start having more distributions which need to do things their own way it will quickly become messy
isn't there a way to delegate the handling of the initial tree directly to `base_distribution` ?

**Comment by davidcerny** [comment]
@bjoelle Hmm, I guess to me this solution didn't seem that bad, because the code that actually does the work is packaged into a separate function (`TreeUtilities::startingTreeInitializer()`), and what's duplicated between distributions is just a function call plus some basic exception handling.

For the particular case from #477, i.e., `dnConstrainedTopology` + `dnBDSTP`, the base distribution _does_ handle the initial tree already, but it doesn't help, because `dnConstrainedTopology` goes on to ignore whatever initial tree the base distribution used (or modified). So maybe a better way to go about things would be to allow `dnConstrainedTopology` to pull the initial tree from its base distribution and set it as its own initial tree. But that would also require some amount of special handling, because not all base distributions (AFAIK) support user-specified initial trees.

**Comment by bjoelle** [comment]
I guess I just feel like the `dnConstrainedTopology` should not be the one knowing/caring about fossil special handling ?
is there a way to create a `setInitialTree` function in tree distributions which gets called as `base_distribution -> setInitialTree` and then the BDSTP can do the special handling there ?
maybe this gets too complicated and I'm worrying about nothing...

**Comment by bredelings** [comment]
I kind of like the structure that Joelle suggested, because it seems like tree distributions could apply arbitrary properties to their trees, and only the distribution would know what those properties are.  In this case, the property is taxon ages, but other tree distributions could in theory add other things.

From another perspective, maybe the problem is that taxon names and taxon properties are confused by having a Taxon object?  That is, it isn't possible to specify just the name, since a Taxon object contains both.  A tree should just specify the taxon _name_, and taxon properties should really be a different thing. 

At an even higher level, the fact that there is such high demand for initial trees really indicates that we should get around to fixing the problem where an initial tree is needed to start the MCMC... but that can't be fixed here.

**Comment by bredelings** [comment]
Maybe we should merge this as is, but add a TODO or FIXME note to reimplement it better later?  That way the best does not become the enemy of the good.

**Comment by davidcerny** [comment]
Sorry for the delay in replying; it's been a busy few days.

I was actually going to ask how we should proceed. I don't insist on having this merged if it doesn't look like a good idea, but since the issue is real and fixable, we should fix it in some other way instead. I agree 100% it would be more satisfying to solve it at a higher level of abstraction, possibly by circumventing the need for a user-specified initial tree altogether. But the progress on making this happen has been very slow (I distinctly remember us having the exact same discussion at the SSB 2023 meeting a year and a half ago!), and people should be able to run their analyses even before these more fundamental solutions have finally been implemented.

If I understand @bjoelle's idea correctly, a member function called `setInitialTree` would be added to those distributions that currently accept an `initialTree` argument (which, aside from `dnConstrainedTopology` itself, would seem to be just `dnBDSTP` and its derived classes, `dnOBDP`, and `dnEBDP`, though `dnUniformSerialSampledTimeTree` could arguably also benefit from it). When the `initialTree` argument isn't `NULL`, this function would be called by the distribution's constructor, but it could also be called from outside the distribution by `dnConstrainedTopology`. There would have to be some way for `dnConstrainedTopology` to check whether its `base_distribution` does in fact contain the `setInitialTree` member function. (Alternatively, we could add an `initialTree` argument and a `setInitialTree`member function to _all_ tree distributions, but that would be a pretty far-reaching change, especially if we eventually want to eliminate the need for initial trees altogether.)

Does that sound right, and is that what I should aim for instead?

**Comment by davidcerny** [comment]
> Alternatively, we could add an initialTree argument and a setInitialTreemember function to all tree distributions, but that would be a pretty far-reaching change

Hmm... it sounds like @mlandis's suggestion of including an `initValue` argument as deep as `TypedDistribution<T>` and letting inheritance take care of things would make this a lot easier, if we want to go down that route.

**Review by bredelings — APPROVED** [review]

**Pull request merged**
