### PR TITLE
Document `model`

### PR DESCRIPTION
**Pull request by ms609**
Outline the basic use of `model()`, and highlight the `.graph()` method.

The function is not so complicated, but I thought it worth noting that it works with copies of workspace objects (per #524) – perhaps this doesn't necessarily earn a place in the example, but I figured, why not angle for maximum clarity and include this in the example code as well as §Details.

### CODE REVIEW

**Review by davidcerny — CHANGES_REQUESTED** [review]
I think you need to run `./help/md2help.pl` to add the changed content of `./help/md/model.md` to `./src/core/help/RbHelpDatabase.cpp`. This makes it accessible from the console.

**Comment by ms609** [comment]
When I run  `$ perl md2help.pl` (on Windows 10)

I see
```
/**
 * This file was generated automatically.
 * It is not intended to be human readable.
 * See help/README.md for details.
 */

#include "RbHelpDatabase.h"

using namespace std;

RevBayesCore::RbHelpDatabase::RbHelpDatabase()
{
}
```

No files (at least none tracked by git) are modified.

**Comment by davidcerny** [comment]
You're right; I don't think the script works as described / intended. I had to run it like this: `perl md2help.pl md/model.md`, and even then it just printed text to the console that I then had to insert into `RbHelpDatabase.cpp` manually. Could you please do that? Happy to merge afterwards.

**Comment by davidcerny** [comment]
Good point! Let's bring that conversation to Slack, perhaps?

**Review by davidcerny — APPROVED** [review]

**Comment by davidcerny** [comment]
Hmm... it looks like the replacement of `help_arrays` by `help_strings` in the regenerated `RbHelpDatabase.cpp` file breaks the "References" and "See also" sections in some cases – they won't even show up in the console. (E.g., compare the output of running `?dnBivariatePoisson` on this branch and on development.) Not merging this quite yet.

**Comment by bredelings** [comment]
I regenerated the help database and squashed some of the changes.

I wasn't able to push to this branch on @ms609 's repo -- I pushed to a new branch and made a new PR #538.  

I'm not quite sure why I was able to generate the missing sections.  I ran `projects/cmake/build.sh` and also `projects/meson/generate.sh`.

**Pull request closed without merging**
