### PR TITLE
Type conversion fix

### PR DESCRIPTION
**Pull request by bjoelle**
This PR is designed to fix the type conversion system to avoid issues such as #435 
Basically instead of doing implicit conversions under the hood, all conversions now go through `TypeConversionFunction` and create an actual `DeterministicNode` in the graph

The goal is to switch all types to using the new system (instead of just `Integer` currently) but I would like some feedback first so I'm leaving this as draft for now

### CODE REVIEW

**Comment by bjoelle** [comment]
@bredelings it's because the upstream code in `ArgumentRule::fitArgument` also does special handling on constant nodes (i.e. when the object is constant it replaces it instead of creating a new variable, which destroys the original node and so invalidates the deterministic node)
I could change it throughout but my guess is that deterministic nodes are not needed when the underlying value cannot change, and replacing is likely faster in that situation

**Comment by bredelings** [comment]
> @bredelings it's because the upstream code in `ArgumentRule::fitArgument` also does special handling on constant nodes (i.e. when the object is constant it replaces it instead of creating a new variable, which destroys the original node and so invalidates the deterministic node) I could change it throughout but my guess is that deterministic nodes are not needed when the underlying value cannot change, and replacing is likely faster in that situation

Yeah.  Can you put a comment about this?

**Comment by bredelings** [comment]
I wonder how to think about creating new DagNodes on the fly like this.  Can we assume that each conversion will only happen once?  Could we create a second duplicate conversion DagNode, and then leak the first one?

**Comment by bjoelle** [comment]
this is a good question - at the moment nothing seems to be checking whether the conversion already exists, so I think you could indeed end up with a bunch of duplicated conversion nodes, although I think the chances it would actually happen are quite low
I suppose you could do some sort of model graph parsing to check if a node you want already exists and use that one, but that seems quite convoluted - honestly at that point it may be easier to just simplify the type system already

**Comment by bredelings** [comment]
> this is a good question - at the moment nothing seems to be checking whether the conversion already exists, so I think you could indeed end up with a bunch of duplicated conversion nodes, although I think the chances it would actually happen are quite low I suppose you could do some sort of model graph parsing to check if a node you want already exists and use that one, but that seems quite convoluted - honestly at that point it may be easier to just simplify the type system already

In theory we could create a new conversion node for each function that takes the integer node as input and converts it to something.  That's probably fine -- creating and re-using a single conversion node is more like a CSE optimization.

I think as long as we aren't creating new conversion nodes on successive MCMC iterations it is fine for now.

**Comment by bjoelle** [comment]
that sounds like a good idea, I'm not sure where would be the best place - just as an added doc to the conversion function ?

**Comment by bredelings** [comment]
> that sounds like a good idea, I'm not sure where would be the best place - just as an added doc to the conversion function ?

For now, perhaps that is the best place?

There could be more places that we want to add new deterministic nodes in the future.  If so we could add a utility wrapper function and move the docs there, but for now the conversion function is probably fine.

**Review by bredelings — APPROVED** [review]

**Pull request merged**
