### PR TITLE
Fix likelihood bug in PhyloBrownianProcessREML

### PR DESCRIPTION
**Pull request by willpett**
A bug in `PhyloBrownianProcessREML` erroneously updated the root mean estimate before it was used in the computation of the root contrast, causing the likelihood to be computed incorrectly for unrooted trees. This solves #85.

### CODE REVIEW

**Review by hoehna — DISMISSED** [review]
I think the check for zero branch length was necessary for some situations before. Simply removing might be dangerous.

Good catch for the update of the root mean. Since we are fixing this specific bug, we should also fix the exact same issue in:
- PhyloBrownianProcessMultiSampleREML
- PhyloMultiSampleOrnsteinUhlenbeckProcessREML
- PhyloOrnsteinUhlenbeckREML
possibly also for
- PhyloMultivariateBrownianProcessREML
- PhyloMultivariateBrownianProcessMultiSampleREML

**Comment by willpett** [comment]
Thanks for taking a look!
- If a check for zero-length branch lengths is necessary, I think it should be done at the likelihood computation level (i.e. return neginf) instead of arbitrarily setting the branch length to 1e-16.
- I will go ahead and fix the same bug in other models.

**Comment by willpett** [comment]
This doesn't seem to be an issue for the OU REML classes.

**Comment by willpett** [comment]
I checked all the occurrences of `computeBranchTime` and I don't see any obvious reason why a zero-length branch should cause an issue. If there is an instance where it causes a problem, I think implementing a check in the affected model is the proper way to handle it, which is beyond the scope of this pull request. More integration tests for continuous character models are needed.

**Review by willpett — COMMENTED** [review]
Looks ok to me.

**Comment by bredelings** [comment]
> I checked all the occurrences of `computeBranchTime` and I don't see any obvious reason why a zero-length branch should cause an issue. If there is an instance where it causes a problem, I think implementing a check in the affected model and either throwing an exception or returning `-inf` is the proper way to handle it, which is beyond the scope of this pull request. In the meantime, any hypothetical problem will be much easier to identify if it manifests as a crash/error rather than an incorrectly sampled posterior, so I think removing the check is appropriate.

That seems reasonable to me...

**Review by bjoelle — APPROVED** [review]

**Pull request merged**
