### PR TITLE
Build and test Windows using meson cross compile and wine

### PR DESCRIPTION
**Pull request by njbooher**
It builds. Caching is currently off. And tests are failing for some reason.

Making the PR to request @bredelings advice on cleaning it up.

### CODE REVIEW

**Comment by bjoelle** [comment]
The test failures could be tied to the path being different in Windows ? - see issue #50

**Comment by njbooher** [comment]
Ah. That would make sense. Will worry about it next week.

**Comment by bredelings** [comment]
Woah, cool stuff!  I haven't looked at the cross-build stuff in a while, I hope the `make_winroot.sh` script was useful.  I think meson may have gotten a bit more proficient in handling pkg-config for cross-compiles, but I haven't had a chance to look at that yet.

I was going to look into running a build _on windows_, but didn't get too far.  There are a few  issues about this:
https://github.com/actions/virtual-environments/issues/30
https://github.com/actions/starter-workflows/issues/95

There is also this "action":
https://github.com/numworks/setup-msys2

**Comment by njbooher** [comment]
The windows version apparently defaults the working directory to the path the executable lives in rather than the directory you run it from in the shell.

https://github.com/revbayes/revbayes/blob/9a1fcdf469613c494041a2d7e38a583c050f75a4/src/core/utils/RbSettings.cpp

**Comment by njbooher** [comment]
Well, at least the tests run now.

**Comment by bredelings** [comment]
I feel like I remember problems making my laptop run tests on other tools with wine due to DLL issues.

**Comment by njbooher** [comment]
I worked around the default working directory difference by copying the executable to the test directory for each test. The DLL issues mentioned were just me forgetting that executable depended on dlls in the directory I copied it from, so now it's copying those too. It's a massive hack, but works for now.

The tests run now. Initially they failed due to line endings differences in the output (\r\n vs \n), but that's now fixed. Now several of them pass. The current failures seem to be due to differences in floating point formatting. (e.g. 6.96098e-005 vs 6.96098e-05). I changed the actions config to upload the output of the tests when they fail as an artifact. You can view it if you want by going to [the job log page](https://github.com/revbayes/revbayes/pull/62/checks?check_run_id=586429813), clicking 'Artifacts', then 'test-results' in the dropdown.

**Comment by njbooher** [comment]
Tests seem to be passing now.

**Pull request merged**
